### ISSUE TITLE
thiết kế, làm trang upload sản phẩm, danh mục sản phẩm

### ISSUE THREAD

**Issue by nmquang21** [trannhuson/SE03-Group02#16]

**Comment by viethai-tr** [comment]
để mỗi bộ nhớ làm 1 product mới nhé?

**Comment by viethai-tr** [comment]
ah mà up nhiều ảnh lên product images thì trang bán hàng nó hiển thị nnao

**Comment by trannhuson** [comment]
1 ảnh cũng dc , hoặc là nếu up nhiều ảnh thì để cố định ảnh đầu tiên là ảnh
đẹp nhất vậy sau cho dễ chọn

Vào 23:31, T.2, 16 Th12, 2019 Viet Hai <notifications@github.com> đã viết:

**Comment by viethai-tr** [comment]
nó tự động để ảnh đầu tiên là to nhất đúng k?
thế ảnh mình lưu vào đâu

**Comment by trannhuson** [comment]
Dc ko nhỉ

Vào 23:34, T.2, 16 Th12, 2019 Như Sơn Trần <nhusonnb98@gmail.com> đã viết:

**Comment by trannhuson** [comment]
Tạo 1 thư mục image riêng trong project

Vào 23:34, T.2, 16 Th12, 2019 Viet Hai <notifications@github.com> đã viết:

**Comment by nmquang21** [comment]
1 cái làm ảnh chính, mấy cái còn lại là thumbnail, nhỏ nhỏ ở dưới, chon thì to lên

**Comment by viethai-tr** [comment]
![image](https://user-images.githubusercontent.com/56261531/70925816-7f1f6500-205e-11ea-8012-de2de9b43e40.png)
có vẻ oke r, b nào chỉnh lại hộ tên với title bảng với nhé

**Comment by viethai-tr** [comment]
![image](https://user-images.githubusercontent.com/56261531/70927306-5056be00-2061-11ea-8f21-0f8ef647f280.png)
add thêm hiện dc có 5 sp, mà k dùng dc nút sửa với xóa
trong database vẫn hiện bth

**Comment by viethai-tr** [comment]
sao list chỉ hiện dc có 5 sp nhỉ
brand cx thế

**Comment by viethai-tr** [comment]
cái màu của button Edit với Delete trong Brand mình sửa lại cho đồng bộ nhé
cái mục khác màu 2 button nó khác nhau

**Comment by viethai-tr** [comment]
@hoanggminh2702 hnay hoặc mai xong dữ liệu bảng Product nhé để t đổ nốt mấy bảng phụ

**Comment by viethai-tr** [comment]
ảnh sp nhớ cho vào public/uploads/product_images nhé
thư mục đấy trong branch t có rồi, pull về thử xem

**Comment by viethai-tr** [comment]
@hoanggminh2702 làm xong chưa?
