### ISSUE TITLE
Chốt đề tài dự án

### ISSUE THREAD

**Issue by nmquang21** [trannhuson/SE03-Group02#2]

**Comment by trannhuson** [comment]
web bán hàng có nhiều loại mặt hàng à

**Comment by nmquang21** [comment]
chắc bán 1 loại thôi, ví dụ đồ điện tử, thời trang,...

**Comment by trannhuson** [comment]
Bán đồ điện tử nhé

Vào 14:51, CN, 3 Th11, 2019 nmquang21 <notifications@github.com> đã viết:

**Comment by nmquang21** [comment]
thế đặt là TechShop, hay là ElecShop

**Comment by trannhuson** [comment]
Cái nào cũng dc , thử tạo r đăng lên

Vào 14:55, CN, 3 Th11, 2019 nmquang21 <notifications@github.com> đã viết:

**Comment by nmquang21** [comment]
ko commit đc mà

**Comment by trannhuson** [comment]
Để t xem nã , m làm nhóm trưởng luôn nhá

Vào 14:59, CN, 3 Th11, 2019 nmquang21 <notifications@github.com> đã viết:

**Comment by nmquang21** [comment]
ừ, commit đc rồi

**Comment by viethai-tr** [comment]
uh làm kiểu cửa hàng bán luôn ấy đừng làm chợ

**Comment by trannhuson** [comment]
Thế chốt là dùng Laravel php

**Comment by trannhuson** [comment]
Quang làm nhóm trưởng nhé

**Comment by hoanggminh2702** [comment]
ừ Quang làm trưởng nhóm đi ông
