### ISSUE TITLE
Làm các chức năng thêm,sửa,xóa danh mục sản phẩm trang admin

### ISSUE THREAD

**Issue by trannhuson** [trannhuson/SE03-Group02#20]
T vừa push lên cái thêm sửa xóa cái category vs brand rồi đấy,mọi người pull về xem có lỗi gì ko

**Comment by viethai-tr** [comment]
thêm function sửa xóa trong mục Products nữa
có button sẵn rồi

**Comment by nmquang21** [comment]
cái đấy cứ tưởng trước sơn làm rồi mà, bảo sơn vào lại xem

**Comment by trannhuson** [comment]
Cái bảng product ngày trước t tưởng m lm xong r @mquang , thôi để t xem lại
cho

Vào 14:11, T.3, 31 Th12, 2019 nmquang21 <notifications@github.com> đã viết:
