### ISSUE TITLE
Làm chức năng đăng nhập trang Admin

### ISSUE THREAD

**Issue by nmquang21** [trannhuson/SE03-Group02#22]

**Comment by trannhuson** [comment]
t vừa đẩy code lên r đấy

**Comment by trannhuson** [comment]
@nmquang21  sao t sửa mãi mà nó ko ra được cái dấu tích chỗ nhớ mật khẩu ý

**Comment by nmquang21** [comment]
kệ nó đã, cứ làm đăng nhập được đi

**Comment by nmquang21** [comment]
làm cả cái middeware, phải đăng nhập ms vào được trang admin

**Comment by nmquang21** [comment]
không đăng nhập mà vào url phải đẩy ra trang đăng nhập

**Comment by trannhuson** [comment]
Đăng nhập admin hôm qua t lm r

Vào 14:09, T.3, 31 Th12, 2019 nmquang21 <notifications@github.com> đã viết:

**Comment by nmquang21** [comment]
@trannhuson  Làm ok chức năng này chưa

**Comment by nmquang21** [comment]
xử lí cả middleware nữa

**Comment by trannhuson** [comment]
Ok r

Vào 23:44, T.3, 7 Th1, 2020 nmquang21 <notifications@github.com> đã viết:

**Comment by nmquang21** [comment]
ok

**Comment by trannhuson** [comment]
đóng issue nhé
