### ISSUE TITLE
Làm chức năng đăng nhập , đăng kí người dùng

### ISSUE THREAD

**Issue by nmquang21** [trannhuson/SE03-Group02#23]

**Comment by nmquang21** [comment]
sơn vs minh làm cả cái đăng kí đăng nhập trang người dùng nhá

**Comment by trannhuson** [comment]
Ok

Vào 14:10, T.3, 31 Th12, 2019 nmquang21 <notifications@github.com> đã viết:

**Comment by nmquang21** [comment]
@trannhuson , @hoanggminh2702  tình hình sao rồi ae

**Comment by trannhuson** [comment]
Chưa lm , đợi thi xong Ai nã 😄 , cái đấy chắc lm nhanh

Vào 23:45, T.3, 7 Th1, 2020 nmquang21 <notifications@github.com> đã viết:

**Comment by trannhuson** [comment]
Chiều mùng 9 lên tr được ko

Vào 23:47, T.3, 7 Th1, 2020 Như Sơn Trần <nhusonnb98@gmail.com> đã viết:

**Comment by trannhuson** [comment]
@viethai-tr  cái bảng customers là nó liên kết vs những bảng nào nhỉ

**Comment by viethai-tr** [comment]
có bảng bills để làm đơn hàng

**Comment by trannhuson** [comment]
ohh , của t thiếu bảng bills

**Comment by viethai-tr** [comment]
cả wishlist nữa

**Comment by trannhuson** [comment]
lại phải cập nhật migration à

**Comment by viethai-tr** [comment]
đăng nhập với đăng ký ổn r nhé, dùng bảng customer trong database

**Comment by trannhuson** [comment]
Trang admin lúc đăng nhập vào nó đã đổi tên dc chưa

Vào 04:06, T.7, 11 Th1, 2020 Viet Hai <notifications@github.com> đã viết:
