### ISSUE TITLE
Trang chi tiết sản phẩm

### ISSUE THREAD

**Issue by viethai-tr** [trannhuson/SE03-Group02#35]
sửa dc lỗi css rồi nma detail trong db có ảnh mà in ra bị lỗi rồi

**Comment by trannhuson** [comment]
Lỗi cái header đấy á

Vào 17:02, T.6, 10 Th1, 2020 Viet Hai <notifications@github.com> đã viết:

**Comment by viethai-tr** [comment]
không fai
lỗi của detail thôi

**Comment by trannhuson** [comment]
Gửi hình xem nào

Vào 17:12, T.6, 10 Th1, 2020 Viet Hai <notifications@github.com> đã viết:

**Comment by viethai-tr** [comment]
để tí gửi cho
tại chắc lúc nhập detail vào nó k đúng định dạng thôi

**Comment by trannhuson** [comment]
Ok

Vào 17:14, T.6, 10 Th1, 2020 Viet Hai <notifications@github.com> đã viết:

**Comment by viethai-tr** [comment]
in ra được detail có ảnh có định dạng chữ rồi nhé

**Comment by trannhuson** [comment]
Đẩy code lên đi e

Vào 00:09, T.7, 11 Th1, 2020 Viet Hai <notifications@github.com> đã viết:

**Comment by viethai-tr** [comment]
ok

Vào Th 7, 11 thg 1, 2020 lúc 00:13 trannhuson <notifications@github.com> đã
viết:

**Comment by viethai-tr** [comment]
thêm danh mục sp khác trong trang chi tiết sp rồi nhé

**Comment by trannhuson** [comment]
Ok bb

Vào 01:46, T.7, 11 Th1, 2020 Viet Hai <notifications@github.com> đã viết:

**Comment by viethai-tr** [comment]
trang chức năng đã có đủ những chức năng cơ bản + show sp khác
