### ISSUE TITLE
làm chức năng đăng nhập, đăng xuất trang chính

### ISSUE THREAD

**Issue by trannhuson** [trannhuson/SE03-Group02#36]

**Comment by trannhuson** [comment]
@nmquang21  code đăng ký hôm qua t đẩy lên r
còn đăng nhập đang bị lỗi

**Comment by nmquang21** [comment]
$2y$10$8nul7ZKpLfOlRd4Oxt/Tx.rzkbQTlwwJ50HILx0uF/EZ.DkMIjLy2

**Comment by nmquang21** [comment]
$2y$10$8nul7ZKpLfOlRd4Oxt/Tx.rzkbQTlwwJ50HILx0uF/EZ.DkMIjLy2
