### ISSUE TITLE
Làm chức năng tạo đơn hàng, lưu đơn hàng vào database

### ISSUE THREAD

**Issue by trannhuson** [trannhuson/SE03-Group02#38]

**Comment by trannhuson** [comment]
cái này xong r thì t đóng issue nhá

**Comment by viethai-tr** [comment]
đóng đi

Vào Th 7, 11 thg 1, 2020 lúc 00:21 trannhuson <notifications@github.com> đã
viết:

**Comment by trannhuson** [comment]
sao lm xong ko cmt vào trong issue

**Comment by nmquang21** [comment]
Cứ nước đến chân ms nhảy =))

**Comment by viethai-tr** [comment]
quên :)

Vào Th 7, 11 thg 1, 2020 lúc 00:25 nmquang21 <notifications@github.com> đã
viết:
