### ISSUE TITLE
Làm chức năng thêm sản phẩm vào danh sách yêu thích

### ISSUE THREAD

**Issue by trannhuson** [trannhuson/SE03-Group02#39]

**Comment by trannhuson** [comment]
lm xong cái này chưa @nmquang21

**Comment by nmquang21** [comment]
Xin lỗi ae , đang lm nốt

**Comment by viethai-tr** [comment]
nhanh lên

Vào Th 7, 11 thg 1, 2020 lúc 00:20 nmquang21 <notifications@github.com> đã
viết:

**Comment by viethai-tr** [comment]
đã add được vào wishlist từ homepage và category
