### ISSUE TITLE
Thiết kế cơ sở dữ liệu

### ISSUE THREAD

**Issue by trannhuson** [trannhuson/SE03-Group02#4]

**Comment by viethai-tr** [comment]
csdl dùng sql server nhé?

**Comment by trannhuson** [comment]
Dùng mysql ấy

Vào 17:56, T.2, 11 Th11, 2019 Viet Hai <notifications@github.com> đã viết:

**Comment by trannhuson** [comment]
Để tí t tải cái database lên , mn xem qua xem có dc ko

Vào 17:56, T.2, 11 Th11, 2019 Viet Hai <notifications@github.com> đã viết:

**Comment by viethai-tr** [comment]
uh cứ làm khung trước r về sau thêm cx dc

**Comment by trannhuson** [comment]
[database.zip](https://github.com/trannhuson/SE03-Group02/files/3831744/database.zip)
mọi người xem qua cái csdl này xem có được không

**Comment by viethai-tr** [comment]
db này giống trong tutorial ah?
để t làm thử tạo model các thứ

**Comment by viethai-tr** [comment]
tạo xong db rồi
để đổ dl test trước nhé
oke thì đổ full sau

**Comment by viethai-tr** [comment]
[se03_db.zip](https://github.com/trannhuson/SE03-Group02/files/3864479/se03_db.zip)
tạm thời nnay nhé
để nghiên cứu quan hệ users với customer có gì sửa lại sau

**Comment by viethai-tr** [comment]
ah để thêm bảng màu sắc dung lượng các thứ, htrc k nghĩ ra

**Comment by viethai-tr** [comment]
vừa bỏ cột category_id ở table Brands nhé

**Comment by viethai-tr** [comment]
t vừa commit code đoạn seed dữ liệu vào database đấy, để pull code giao diện admin về add nốt vào bảng Products

**Comment by viethai-tr** [comment]
Xóa cột category id xong bảng Brands xong thì sửa code chức năng add Brand ở chỗ nào nhỉ

**Comment by trannhuson** [comment]
Sửa cái brand để t sửa cho , t lm cái đấy mà

Vào 23:00, T.2, 16 Th12, 2019 Viet Hai <notifications@github.com> đã viết:

**Comment by viethai-tr** [comment]
ai sửa hộ code đoạn import into Brands xong push lên hộ với

**Comment by trannhuson** [comment]
T 2 hôm nữa ms lên hn

Vào 23:13, T.2, 16 Th12, 2019 Viet Hai <notifications@github.com> đã viết:

**Comment by viethai-tr** [comment]
ah làm dc r
quên k để Name trong bảng Brand làm primary key mất rồi

**Comment by viethai-tr** [comment]
nên chia ra mỗi category 1 bảng không?

**Comment by nmquang21** [comment]
hải thiết kế cái diagram database xong up ảnh lên đây cho dễ hình dung database nhá

**Comment by viethai-tr** [comment]
okr

Vào Th 7, 11 thg 1, 2020 lúc 00:13 trannhuson <notifications@github.com> đã
viết:
