### ISSUE TITLE
Làm chức năng đăng nhập, đăng xuất trang admin

### ISSUE THREAD

**Issue by trannhuson** [trannhuson/SE03-Group02#40]

**Comment by trannhuson** [comment]
đăng nhập trang admin có lỗi gì ko ae

**Comment by nmquang21** [comment]
Ko , vẫn bt

**Comment by viethai-tr** [comment]
lm xong r thì đóng issue lại đi

Vào Th 7, 11 thg 1, 2020 lúc 00:17 nmquang21 <notifications@github.com> đã
viết:

**Comment by trannhuson** [comment]
ok
