### ISSUE TITLE
Cắt giao diện chính

### ISSUE THREAD

**Issue by trannhuson** [trannhuson/SE03-Group02#8]

**Comment by trannhuson** [comment]
Quang ơi tí rảnh ko , vào teamview cho t 1 ít , t cắt giao diện sao nó ko hiển thị dc ảnh

**Comment by nmquang21** [comment]
@trannhuson làm phần giao diện ok rồi chứ?

**Comment by trannhuson** [comment]
mới chỉ cắt trang dc thôi , còn chưa cho dữ liệu vào

**Comment by trannhuson** [comment]
Thứ 4 tuần này lại lên trường làm nhé , dc ko

**Comment by trannhuson** [comment]
t đẩy code lên r đấy

**Comment by nmquang21** [comment]
Ok, thứ tư mọi người lên trường để thao luận chút về đề tài nhá

**Comment by nmquang21** [comment]
anh em vào trang này xem nhiều giao diện đẹp lắm, hình như toàn miễn phí https://themehunt.com/

**Comment by trannhuson** [comment]
@mquang m tìm đi , t toàn tìm cái ko hợp vs ý của m

Vào 23:42, T.2, 9 Th12, 2019 nmquang21 <notifications@github.com> đã viết:

**Comment by trannhuson** [comment]
t vừa cắt xong trang giao diện chính còn lại r
